apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::939789941218:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::939789941218:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::939789941218:role/ek>
  creationTimestamp: "2022-10-06T20:41:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "17658"
  uid: 4eadef55-d588-4542-8617-a5405641e6f0
